Add new differential functionality
ubermag/discretisedfield pull request #208
Opened 2022-11-14 11:18 UTC by samjrholt

2022-11-28 15:24 UTC, lang-m requested changes
The changes in the code look good. I commented on a few minor things.

In the tests we are using `np.isclose` and `np.allclose` inconsistenly. It propably does not matter. Is there any particular reason for doing so.

I did not check all the tests in detail (i.e. compute the derivatives to check if the tests are actually correct). I assume you have checked it?

2022-11-28 15:24 UTC, lang-m commented on discretisedfield/field.py
>          )
The extra square brackets can be removed.

2022-11-28 15:24 UTC, lang-m commented on discretisedfield/field.py
>      def div(self):
The double backslashes in the docstring have to be changed to single backslashes (because it is a raw string). Probably also in the other docstrings.

2022-11-28 15:24 UTC, lang-m commented on discretisedfield/field.py
>                  for i in range(self.nvdim)
```suggestion
                getattr(self, vdim).diff(vdim) for vdim in self.nvdim
```

2022-11-28 15:24 UTC, lang-m commented on discretisedfield/tests/test_field.py
> +        # No Neumann
No Dirichlet?

2022-11-28 15:24 UTC, lang-m commented on discretisedfield/tests/test_field.py
> +        # Neumann
Dirichlet?

2022-11-29 10:23 UTC, samjrholt commented on discretisedfield/field.py
> +            padding_mode = "symmetric"
You are correct, they are equivalent for a single cell but not for more.
`edge` : `abcde|eee`
`symmetric` : `abcde|edc`

2022-11-29 11:23 UTC, samjrholt commented
> The changes in the code look good. I commented on a few minor things.
> 
> In the tests we are using `np.isclose` and `np.allclose` inconsistenly. It propably does not matter. Is there any particular reason for doing so.
> 
> I did not check all the tests in detail (i.e. compute the derivatives to check if the tests are actually correct). I assume you have checked it?

I have gone through and changed `np.isclose` to `np.allclose` for consistency.
I have also checked the values for the tests given the correct boundary conditions. (And now added those that were missing)

2022-11-29 14:56 UTC, lang-m approved these changes
Looks good to me. You can merge.

2022-11-29 15:04 UTC, merged