Derivatives
ubermag/discretisedfield pull request #272
Opened 2022-12-14 17:54 UTC by samjrholt

2023-01-11 15:28 UTC, samjrholt commented
@lang-m take a quick look through the logic of the new derivative method. There is a lot of cleaning up to-do but I can start to do that if we are happy with the rough outline.

2023-01-11 15:54 UTC, lang-m reviewed
I had a look at the implementation (ignored the tests). Looks good to me. We could consider moving the "utility" methods (which are currently class methods) to the `operator` submodule [or make them static methods (`@staticmethod` without `self`)].

The comments in the code are very useful!

I'll have a more detailed look once you are done with cleaning up.

2023-01-12 08:56 UTC, lang-m requested changes
Looks good overall. I left a few minor comments.

I cannot really comment on the `sympy` tests.

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/operators.py
> +        if len(array) > 3:
```suggestion
        if len(array) < 3:
            # Second order accuracy is in the center of the array and
            # first order at the boundaries.
            derivative_array = np.gradient(array, dx, edge_order=1)
        else:
```

We can use `edge_order=2` already for 3 elements.

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/operators.py
> +        if len(array) > 4:
Could this be `>= 4`?

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/operators.py
> +        derivative_array = np.convolve(array, [1, -2, 1], "same")
Just to clarify, this computes wrong values at the boundary?

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/operators.py
> +        array[loc[i] + 1 : loc[i + 1]]
Could you please explain the `loc[i] + 1`, in particular the `+ 1` in a comment in the code.

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/operators.py
> +    on based on contiguous valid values,
```suggestion
    based on contiguous valid values,
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_field.py
> +    p1 = (0, 0, 0)
```suggestion
    # 3d mesh
    p1 = (0, 0, 0)
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_field.py
> +def test_diff_valid():
Please add a second example on a 1d mesh with floating-point values and a valid array with single-element sections, i.e. something like:

```suggestion
def test_diff_valid():
    # 1d mesh
    mesh = df.Mesh(p1=-5e-9, p2=10e-9, n=10)
    valid = [True, False, False, True, True, True, False, True, False, False]
    f = df.Field(mesh, nvdim=1, value=lambda p: (p[0] * 1e9)**2, valid=valid)
    
    # TODO add tests
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_operators.py
> +    assert all([isinstance(sublist, np.ndarray) for sublist in split_list])
```suggestion
    assert all(isinstance(sublist, np.ndarray) for sublist in split_list)
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_operators.py
> +    assert sum([len(sublist) for sublist in split_list]) == sum(valid)
```suggestion
    assert sum(len(sublist) for sublist in split_list) == sum(valid)
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_operators.py
> +    assert all([num not in flat_list for num in missing])
```suggestion
    assert all(num not in flat_list for num in missing)
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_operators.py
> +        [True, False, True, False, True],
Test a sequence of `False`

```suggestion
        [True, False, True, False, True],
        [False, False, False, True, True, False],
```

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_operators.py
> +    assert len(out) == len(array)
It might be good to also check the actual values.

2023-01-12 08:56 UTC, lang-m commented on discretisedfield/tests/test_operators.py
> +            print(diff_array)
Debug prints?

2023-01-12 08:57 UTC, samjrholt commented
@lang-m the failing `discretisedfield/tests/test_field.py::test_integrate_cumulative` test is due to casting a `float` to an `int` somewhere but I am not sure where that actual issue lies.

2023-01-12 08:59 UTC, lang-m commented
Sympy is missing as a dependency (for testing).

2023-01-12 09:16 UTC, samjrholt commented on discretisedfield/field.py
> +                out[tuple([*idx, dim])] = _split_diff_combine(
Tuple requires 1 argument so I will leave this as is.

2023-01-12 15:34 UTC, lang-m approved these changes
Looks all good to me. Last suggestion: we could move `_split_diff_combine` towards the top of the file, to the beginning of the derivative functions. That could be useful because it is a better starting point when trying to follow the derivative calculation.

2023-01-12 15:34 UTC, lang-m commented on discretisedfield/operators.py
> +    # as the current one, we do not want to create a slice.
Very nice!

2023-01-12 15:38 UTC, merged