fft updates
ubermag/discretisedfield pull request #326
Opened 2023-01-16 09:27 UTC by samjrholt

2023-01-16 16:47 UTC, samjrholt commented
@lang-m the main thing still to talk about is I've split real fft and normal fft in field but not in mesh. However, it may be nice if this is consistent.

2023-01-17 08:29 UTC, lang-m reviewed
I have so far only reviewed small parts of the code. There is quite a bit of duplication that I would like to remove. Before changing anything we should make a decision on whether to keep or drop `[i]rfftn`.

2023-01-17 08:29 UTC, lang-m commented on discretisedfield/field.py
> +        axes = np.arange(self.mesh.region.ndim)
FFT did use `range`, here you use `np.arange`. Is there any reason for the difference?

2023-01-17 08:29 UTC, lang-m commented on discretisedfield/field.py
> +            vdims = [ftvdim[3:] for ftvdim in self.vdims]
We should probably check if `ftvdim` starts with `ft_`.

2023-01-17 08:29 UTC, lang-m commented on discretisedfield/field.py
> +                    vdim_mapping[vdim] = self.vdim_mapping[ft_vdim][2:]
Check if the dim starts with `k_`.

2023-01-17 08:29 UTC, lang-m commented on discretisedfield/field.py
> +            vdims = [ftvdim[3:] for ftvdim in self.vdims]
If not, I would maybe use it unchanged.

2023-01-17 08:29 UTC, lang-m commented on discretisedfield/mesh.py
> +                )
I would move this check up to do it right before you test `array_equal`.

2023-01-17 08:29 UTC, lang-m commented on discretisedfield/field.py
>      def rfftn(self):
Do we need `rfft` and `irfft` in `mag2exp` (or anywhere else in ubermag)? If not I would suggest that we consider removing it. I would assume that `[i]fftn` should be enough functionality and we would then also avoid the "problem" with the mesh shape in `irfftn`.

2023-01-17 14:17 UTC, lang-m requested changes
In the docstrings we should mention that `subregions` are lost.

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +
```suggestion
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +
```suggestion
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +
```suggestion
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +        1. Perform a real iFFT.
```suggestion
        2. Perform a real iFFT.
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +            ):
Could we simplify and combine this using `... // 2 != ...`?

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +        kdims = [d[2:] for d in self.region.dims if d[:2] == "k_"]
```suggestion
        kdims = [d[2:] if d.startswith("k_") else d for d in self.region.dims]
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/mesh.py
> +        ]
```suggestion
        kunits = [
            u[1:-4] if u.startswith("(") and u.endswith(")^-1") else u
            for u in self.region.units
        ]
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_field.py
> +    for dim in ["x", "y", "z"]:
```suggestion
    for dim in "xyz":
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_field.py
> +    f = df.Field(mesh, nvdim=1, value=_init_random, norm=1)
```suggestion
    f = df.Field(mesh, nvdim=1, value=np.random.rand(*mesh.n, 1), norm=1)
```

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +    assert np.allclose(mesh_fft.region.pmax, p2)
Apart from the checks for `units` and `dims` you could use `mesh.allclose(mesh_fft)`.

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +    assert np.allclose(mesh_fft.region.pmax, p2)
Apart from the checks for `units` and `dims` you could use `mesh.allclose(mesh_fft)`.

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +    assert np.allclose(mesh_fft.region.pmax, p2)
Apart from the checks for `units` and `dims` you could use `mesh.allclose(mesh_fft)`.

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +    # 3D mesh with odd number of cells
In all tests below use `mesh.allclose(...)` when possible.

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +        [(20, 20, 6), ValueError],
Add brief comments why they fail to the end of the individual lines.
Why do we have the test with `6` and `7`? Do they test different things?

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +        [(20,), ValueError],
brief explanation

2023-01-17 14:17 UTC, lang-m commented on discretisedfield/tests/test_mesh.py
> +        [20, ValueError],
brief explanation

2023-01-17 14:47 UTC, samjrholt commented on discretisedfield/mesh.py
> +
I didn't think we could remove this as we are using `rfftfreq` instead of `fftfreq`

2023-01-17 14:51 UTC, lang-m commented on discretisedfield/mesh.py
> +
I thought I had a separate comment that moved the functionality to a different part of the method (now I can't find it). Anyways, I'll have an other look when you are done.

2023-01-17 15:39 UTC, lang-m reviewed
Could you please add ``**kwargs`` to the docstrings.

2023-01-17 16:12 UTC, merged